import Head from 'next/head';
import styles from '../styles/Home.module.css';
import useSWR from 'swr';
import { useEffect } from 'react';

export default function Home() {
  const { data } = useSWR('/auth/me');

  useEffect(() => {
    console.log(data);
  }, [data]);

  return (
    <>
      <Head>
        <title>Lightning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>This is Main Page</main>
    </>
  );
}
